# Generated by Django 5.1.4 on 2025-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='cooking_time',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='serving_size',
            field=models.CharField(max_length=16),
        ),
    ]
