# Generated by Django 5.1.4 on 2025-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipemodel_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(default='value'),
            preserve_default=False,
        ),
    ]
