# Generated by Django 5.1.4 on 2025-01-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipemodel_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
